import "./globals.css";
import { Roboto_Slab } from "next/font/google";
import Header from "@/components/header/Header";
const Roboto = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "Yala-halal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${Roboto.className} `}>
        <header className=" w-full h-16 bg-slate-900 fixed z-50 flex items-center justify-center border-b-2 border-white top-0 left-0 ">
          <Header />
        </header>
        {children}
      </body>
    </html>
  );
}
