import "./globals.css";
import { Roboto_Slab } from "next/font/google";
import Header from "@/components/header/Header";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
const Roboto = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "Yala-halal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${Roboto.className}`} suppressHydrationWarning={true}>
        <AuthProvider>
          <header className=" fixed left-0 top-0 z-50 flex h-16 w-full items-center justify-center border-b-2 border-white bg-darkBlue ">
            <Header />
          </header>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
